<h1>Tournaments</h1>

<div class="action-bar">
    <button class="btn" type="button" onclick="location.href='<?php echo $this->escapeHtml($this->url('lpm_tournament/tournament_add')) ?>'">
        <span class="glyphicon glyphicon-plus"></span> &nbsp; Create new tournament
    </button>
</div>

<?php
echo $this->partial('lpm_tournament/shared/table/tournaments.phtml', array('tournaments' => $this->tournaments));
?>